include: package:very_good_analysis/analysis_options.2.4.0.yaml

analyzer:
  exclude:
    - lib/generated_plugin_registrant.dart
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    public_member_api_docs: false
    ignore: use_late_for_private_fields_and_variables