name: holidays
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  bloc: ^8.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  getwidget: ^2.0.4
  graphql: ^5.0.0
  intl: ^0.17.0

dev_dependencies:
  bloc_test: ^9.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.4

flutter:
  uses-material-design: true
  generate: true
