name: holidays

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.5"

      - name: Install Dependencies
        run: flutter packages get

      - name: Format
        run: flutter format --set-exit-if-changed lib test

      - name: Code Generation
        run: flutter packages run build_runner build --delete-conflicting-outputs

      - name: Analyze
        run: flutter analyze lib

      - name: Build APK
        run: flutter build apk  --flavor production --target lib/main_production.dart

      # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-production-release.apk

      # - name: Run tests
      #   run: flutter test --no-pub --coverage --test-randomize-ordering-seed random

      # - name: Check Code Coverage
      #   uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
